### ISSUE TITLE
802.11w not working?

### ISSUE THREAD

**Issue by schm0** [kaloz/mwlwifi#250] opened 2017-12-28 15:27 UTC
Hi!

Is the 802.11w extension supposed to work properly?
Can you have a look at this thread please
https://forum.lede-project.org/t/wifi-problems-client-connects-inconsistently/9944/14
thank you.

**Comment by yuhhaurlin** [comment] 2018-01-02 03:36
802.11w should work. I close this one first.

**Comment by yuhhaurlin** [comment] 2018-01-02 07:39
I will test it later to make sure it works.

**Comment by yuhhaurlin** [comment] 2018-01-02 11:17
It looks like even though you select wpad (full), the build configuration does not support 802.11w. I just complete the build and I will test it later. However, you can check if you build in 802.11w for hostapd first.

**Comment by schm0** [comment] 2018-01-02 12:47
A happy new year =)
Thank you for looking into this.

I think my build has 802.11w support build in cause my interfaces come up fine?
Why is the rsn capabilities field all zero in the beacons but not in the 3/4 msg of the 4 way handshake?

**Comment by yuhhaurlin** [comment] 2018-01-02 13:44
These things are done by hostapd.

**Comment by schm0** [comment] 2018-01-02 13:45
Doesnt hostapd query the driver for some things?

**Comment by yuhhaurlin** [comment] 2018-01-02 14:05
No. Driver only needs to take care of key setting. I check the code, it should work.

**Comment by yuhhaurlin** [comment] 2018-01-02 14:06
However, I will test it.

**Comment by yuhhaurlin** [comment] 2018-01-03 06:32
RSN IE of beacon and probe response does not include "group management cipher suite". I will check and fix it. Thanks for your information.

**Comment by schm0** [comment] 2018-01-03 06:34
Thank you =)

**Comment by yuhhaurlin** [comment] 2018-01-03 06:37
RSN capability is all right in my test case, but it lacks "group management cipher suite". I will complete the test and update fix once if the problem is fixed.

**Comment by schm0** [comment] 2018-01-03 15:15
Thank you again ;)

**Comment by yuhhaurlin** [comment] 2018-01-04 02:13
It looks like if your use default "group management cipher suite", hostapd won't append this to RSN IE. I will test and make sure all issues are gone, but RSN IE is correct.

**Comment by schm0** [comment] 2018-01-04 10:24
So this is an hostapd issue?
Is there an easy way to fix?

**Comment by yuhhaurlin** [comment] 2018-01-04 10:33
It should be all right for Hostapd to omit announcement of default group management cipher suite. I still check it.

**Comment by yuhhaurlin** [comment] 2018-01-05 06:25
1. You need to make sure your client supports MFP. If it supports MFP, there is no problem for the connection to WRT3200ACM.
2. However, the data path has problem. I will try to fix it.

Station  (on wlan0)
        rx bytes:       6466
        rx packets:     67
        tx bytes:       20975
        tx packets:     196
        tx retries:     0
        tx failed:      0
        rx drop misc:   5
        signal:         -43 dBm
        signal avg:     -39 dBm
        tx bitrate:     6.0 MBit/s
        rx bitrate:     300.0 MBit/s VHT-MCS 7 40MHz short GI VHT-NSS 2
        authorized:     yes
        authenticated:  yes
        associated:     yes
        preamble:       long
        WMM/WME:        yes
        MFP:            yes
        TDLS peer:      no
        DTIM period:    2
        beacon interval:100
        short slot time:yes
        connected time: 17 seconds

**Comment by schm0** [comment] 2018-01-05 11:10
I have a wrt1200ac.

I have to devices i can test with.
One is a samsung s5 with lineage os.

In optional mode the behavior is the same as in the thread i linked.
The device will not connect because rsn compatibility field is different.
However after the 802.11w timeout timer is reached the device connects.
In required mode no connection at all. 

My other device is an wireless network cam.
In required mode the device doesn't connect at all.
In optional mode the device connects immediately. 
Somehow the fallback here is more faster.

Did you manage to fix the blank rsn ccompatibility field?

**Comment by yuhhaurlin** [comment] 2018-01-05 11:38
I have no blank run capability problem. It will reflect required and optional mode.

**Comment by yuhhaurlin** [comment] 2018-01-05 11:40
I only have data path problem. I think 8864 should be all right. After I fix data path problem of 8964, I will try 8864.

**Comment by yuhhaurlin** [comment] 2018-01-05 11:46
BTW, group management cipher suite and MFP capability of RSN IE capability field is controlled by hostapd. If your configuration is correct, hostapd will add related bits to RSN IE capability.

**Comment by schm0** [comment] 2018-01-05 11:59
yuhhaurlin sorry that i wasted your time.
it seems like group_mgmt_cipher has to be set to something.
with the help from jow on the lede/openwrt irc chat i added one line of code (/lib/netifd/hostapd.sh) to set the group_mgmt_cipher to the "default" AES-128-CMAC.
it works now.

thank you very much for your afford.

**Comment by yuhhaurlin** [comment] 2018-01-05 12:26
All right. It looks like 8864 does not have data path problem. I close this issue. I will continue to fix data path problem of 8964.

**Closed by yuhhaurlin** 2018-01-05 12:26 UTC

**Comment by schm0** [comment] 2018-03-04 17:27
With 802.11w enabled.
Arp resolution stops working on my clients.
The Broadcast are not reaching the clients.
Only works for a brief moment after boot.
No im not sure if this a bug from the router or from the clients.
